### PR TITLE
Add custom error messages

### PR DESCRIPTION
**Pull request by ghost**
Using custom error messages instead of require statements safes gas and is easier to read in case of an error.
However, custom error messages where introduced in `0.8.4`.

### CODE REVIEW

**Comment by ghost** [comment]
@mudgen can I do anything to make this merge happen?

**Comment by svak** [comment]
@mudgen do you plan to merge this?

**Comment by mudgen** [comment]
> @mudgen do you plan to merge this?

Perhaps at some point.  Does hardhat and etherscan and/or other tools properly report custom errors?

**Comment by svak** [comment]
> > @mudgen do you plan to merge this?
> 
> Perhaps at some point. Does hardhat and etherscan and/or other tools properly report custom errors?

I'm not sure.
@byterose could you please clarify that?

**Pull request closed without merging**
